server:
  port: 8000


spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: reportes_route
          uri: lb://REPORTE-SERVICE
          predicates:
            - Path=/api/v1/reportes/**

        - id: facturacion_route
          uri: lb://FACTURACION-SERVICE
          predicates:
            - Path=/api/v1/facturacion/**
 
        - id: telemetria_route
          uri: lb://TELEMETRIA-SERVICE
          predicates:
            - Path=/api/v1/telemetria/**

        - id: incidencia_route
          uri: lb://INCIDENCIA-SERVICE
          predicates:
            - Path=/api/v1/incidencias/**

        - id: lectura_route
          uri: lb://LECTURA-SERVICE
          predicates:
            - Path=/api/v1/lecturas/**

        - id: pago_route
          uri: lb://PAGO-SERVICE
          predicates:
            - Path=/api/v1/pagos/**

        - id: balance_route
          uri: lb://BALANCE-SERVICE
          predicates:
            - Path=/api/v1/balances/**

        - id: reparacion_route
          uri: lb://REPARACION-SERVICE
          predicates:
            - Path=/api/v1/reparaciones/**

        - id: socios_route
          uri: lb://SOCIOS-SERVICE
          predicates:
            - Path=/api/v1/socios/**

        - id: notificacion_route
          uri: lb://NOTIFICACION-SERVICE
          predicates:
            - Path=/api/v1/notificaciones/**

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-y6q9.onrender.com/eureka/

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: DEBUG
    reactor.netty: DEBUG
